image: docker:stable
services:
  - name: docker:dind

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

stages:
  - release

before_script:
  - apk --update add --no-cache make git
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

release:
  stage: release
  tags: [linux, docker]
  script:
    - docker info
    - make release
