version: 2
jobs:
  release:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: apk --update add --no-cache make git
      - run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN $DOCKER_REGISTRY
      - run: docker info
      - run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
      - run: make release


workflows:
  version: 2
  build-workflow:
    jobs:
      - release:
          context: docker-deploy
